### PR TITLE
Make iToast compile with and without ARC, modernized code

### PR DESCRIPTION
**Pull request by SebastianKeller**

### CODE REVIEW

**Comment by afollestad** [comment]
I think most of these open pull requests are important

**Comment by ecstasy2** [comment]
I agree, just being too busy recently to maintain the project.
Will try to find sometime to test them soon. Also @afollestad  feel free to merge them and test on your own fork. I would be happy to just code review one single PR if you test it.

**Comment by afollestad** [comment]
@ecstasy2 I'm a college student so that's very understandable :) sounds good

**Comment by SebastianKeller** [comment]
It's been some time since I wrote that PR. If you want me to change the code in any way, please let me know.

**Comment by afollestad** [comment]
@SebastianKeller well currently there's merge conflicts so your pull request must be out dated from the main code base.

**Comment by SebastianKeller** [comment]
Well, you took your time, I wrote that in August last year. I will have a look at it tomorrow.

**Comment by afollestad** [comment]
@SebastianKeller I'm not the dev of this library

**Comment by SebastianKeller** [comment]
No need to feel offended, I try to make it compile, tomorrow

**Comment by afollestad** [comment]
@SebastianKeller offended? Why would I be offended? Like I said, I'm not the dev of this library, the guy at the top is. You're directing your comments at the wrong person.

**Comment by SebastianKeller** [comment]
I'm not directing my comments to anyone specific.

With "you took your time" I meant both of you.
I'm replying via phone, was not sure who's the maintainer of you guys. 

Like I said, I will have a look at that.

**Comment by ecstasy2** [comment]
Hey guys, you are both awesome. Let's keep it that way :-)
It's my fault, I should have reviewed this PR a while back. Thanks @SebastianKeller for the work it is really appreciated.

**Pull request closed without merging**
